In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
file_path = '/content/drive/MyDrive/capstonedata.csv'

In [ ]:
df = pd.read_csv(file_path)

In [ ]:
data_clean = df.copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder
Label_encoder = LabelEncoder()

In [ ]:
data_clean['Person_sex'] = Label_encoder.fit_transform(data_clean['Person_sex'])
data_clean

Year  Month  Weekday  Hour  Severity  Num_vehicles  \
0        2015      1        1    16         2             1   
1        2015      1        1    16         2             1   
2        2015      1        1     7         2             2   
3        2015      1        1     7         2             2   
4        2015      1        1     7         2             2   
...       ...    ...      ...   ...       ...           ...   
1048570  2018      9        2     3         2             2   
1048571  2018      9        2     5         2             1   
1048572  2018      9        2    14         2             2   
1048573  2018      9        2    14         2             2   
1048574  2018      9        2    14         2             2   

         Collision_configuration  Road_configuration  Weather_condition  \
0                              4                   1                2.0   
1                              4                   1                2.0   
2                             31                   2                4.0   
3                             31                   2                4.0   
4                             31                   2                4.0   
...                          ...                 ...                ...   
1048570                       41                   1                3.0   
1048571                       50                   1                3.0   
1048572                       21                   1                1.0   
1048573                       21                   1                1.0   
1048574                       21                   1                1.0   

         Road_surface  ...  Vehicle_type  Vehicle_year  Person_id  Person_sex  \
0                   4  ...             1          2009        1.0           1   
1                   4  ...             1          2009        0.0           0   
2                   3  ...             1          2014        1.0           2   
3                   3  ...             1          2014        2.0           2   
4                   3  ...             1          2014        0.0           0   
...               ...  ...           ...           ...        ...         ...   
1048570             2  ...             1          2009        1.0           0   
1048571             2  ...             1          2006        1.0           1   
1048572             1  ...             1          2014        1.0           2   
1048573             1  ...             1          2014        2.0           1   
1048574             1  ...             1          2013        1.0           1   

         Person_age  Person_position  Person_injury_severity  \
0                64               50                       2   
1                 0                0                       0   
2                27               50                       2   
3                37               13                       2   
4                 0                0                       0   
...             ...              ...                     ...   
1048570           0               11                       N   
1048571          57               11                       2   
1048572          67               11                       1   
1048573          74               13                       1   
1048574          29               11                       2   

         Safety_device_used  Road_user_type Collision_case  
0                         2               0        2218044  
1                         0               0        2218044  
2                         2               0        2218048  
3                         2               2        2218048  
4                         0               0        2218048  
...                     ...             ...            ...  
1048570                  50               1        2589556  
1048571                   2               1        2589557  
1048572                   2               1        2589559  

In [ ]:
data_clean.isna().sum()

Year                          0
Month                         0
Weekday                       0
Hour                          0
Severity                      0
Num_vehicles                  0
Collision_configuration       0
Road_configuration            0
Weather_condition          1827
Road_surface                  0
Road_alignment             2022
Traffic_control               0
vehicle_id                    0
Vehicle_type                  0
Vehicle_year                  0
Person_id                  1252
Person_sex                    0
Person_age                    0
Person_position               0
Person_injury_severity        0
Safety_device_used            0
Road_user_type                0
Collision_case                0
dtype: int64

In [ ]:
import numpy as np
data_clean['Person_sex'] = data_clean['Person_sex'].replace(0, np.nan)

In [ ]:
data_clean.isna().sum()

Year                           0
Month                          0
Weekday                        0
Hour                           0
Severity                       0
Num_vehicles                   0
Collision_configuration        0
Road_configuration             0
Weather_condition           1827
Road_surface                   0
Road_alignment              2022
Traffic_control                0
vehicle_id                     0
Vehicle_type                   0
Vehicle_year                   0
Person_id                   1252
Person_sex                 49152
Person_age                     0
Person_position                0
Person_injury_severity         0
Safety_device_used             0
Road_user_type                 0
Collision_case                 0
dtype: int64

In [ ]:
data_clean.shape

(1048575, 23)

In [ ]:
1 - ((1048575-49152)/1048575)

0.046875044703526214

In [ ]:
data_clean = data_clean.dropna()
data_clean.isna().sum()
data_clean.shape

(994533, 23)

In [ ]:
data_clean = data_clean.drop(['Collision_case'], axis = 1)
data_clean = data_clean.drop(['vehicle_id'], axis = 1)
data_clean = data_clean.drop(['Person_id'], axis = 1)
data_clean = data_clean.drop(['Road_user_type'], axis = 1)

In [ ]:
data_clean

Year  Month  Weekday  Hour  Severity  Num_vehicles  \
0        2015      1        1    16         2             1   
2        2015      1        1     7         2             2   
3        2015      1        1     7         2             2   
5        2015      1        1     7         2             2   
7        2015      1        1    16         2             2   
...       ...    ...      ...   ...       ...           ...   
1048569  2018      9        2     3         2             2   
1048571  2018      9        2     5         2             1   
1048572  2018      9        2    14         2             2   
1048573  2018      9        2    14         2             2   
1048574  2018      9        2    14         2             2   

         Collision_configuration  Road_configuration  Weather_condition  \
0                              4                   1                2.0   
2                             31                   2                4.0   
3                             31                   2                4.0   
5                             31                   2                4.0   
7                              4                   1                4.0   
...                          ...                 ...                ...   
1048569                       41                   1                3.0   
1048571                       50                   1                3.0   
1048572                       21                   1                1.0   
1048573                       21                   1                1.0   
1048574                       21                   1                1.0   

         Road_surface  Road_alignment  Traffic_control  Vehicle_type  \
0                   4             2.0                0             1   
2                   3             1.0               18             1   
3                   3             1.0               18             1   
5                   3             1.0               18             1   
7                   3             4.0               18             1   
...               ...             ...              ...           ...   
1048569             2             1.0               18             1   
1048571             2             1.0               18             1   
1048572             1             1.0               18             1   
1048573             1             1.0               18             1   
1048574             1             1.0               18             1   

         Vehicle_year  Person_sex  Person_age  Person_position  \
0                2009         1.0          64               50   
2                2014         2.0          27               50   
3                2014         2.0          37               13   
5                2010         2.0          43               50   
7                2000         2.0          35               11   
...               ...         ...         ...              ...   
1048569          2003         2.0          50               11   
1048571          2006         1.0          57               11   
1048572          2014         2.0          67               11   
1048573          2014         1.0          74               13   
1048574          2013         1.0          29               11   

        Person_injury_severity  Safety_device_used  
0                            2                   2  
2                            2                   2  
3                            2                   2  
5                            1                   2  
7                            2                   2  
...                        ...                 ...  
1048569                      2                   2  
1048571                      2                   2  
1048572                      1                   2  
1048573                      1                   2  
1048574                      2                   2  

[994533 rows x 19 columns]

In [ ]:
data_clean.isnull().sum()

Year                       0
Month                      0
Weekday                    0
Hour                       0
Severity                   0
Num_vehicles               0
Collision_configuration    0
Road_configuration         0
Weather_condition          0
Road_surface               0
Road_alignment             0
Traffic_control            0
Vehicle_type               0
Vehicle_year               0
Person_sex                 0
Person_age                 0
Person_position            0
Person_injury_severity     0
Safety_device_used         0
dtype: int64

In [ ]:
print(data_clean['Year'].unique())
print(data_clean['Month'].unique())
print(data_clean['Weekday'].unique())
print(data_clean['Hour'].unique())
print(data_clean['Num_vehicles'].unique())
print(data_clean['Weather_condition'].unique())
print(data_clean['Person_injury_severity'].unique())
print(data_clean['Severity'].unique())
print(data_clean['Collision_configuration'].unique())
print(data_clean['Traffic_control'].unique())
print(data_clean['Person_position'].unique())
print(data_clean['Road_alignment'].unique())
print(data_clean['Person_age'].unique())
print(data_clean['Person_position'].unique())
print(data_clean['Person_injury_severity'].unique())
print(data_clean['Safety_device_used'].unique())

[2015 2016 2017 2018]
[ 1  2  3  4  5  6  7  8  9 10 11 12  0]
[1 2 3 4 5 6 7 0]
[16  7 15  9 12 14  6 18  8 17  2 21 22 19  3 10  0 11 13  5 20 23  1  4]
[ 1  2  3  4  5  6 12 19  8 11  7 17 20  9 10 15 31 22 14 13 47 26 21 18
 37  0 16 51 59]
[2. 4. 1. 3. 7. 6. 5. 0.]
['2' '1' 'N' '3' '0']
[2 1]
[ 4 31 21 35  2  3 23 24 22  1 33 50 41  5 32 34  6 36  0 25]
[ 0 18  1 12  6  3 50  2  4  8 15  9  5 16 10 11 13 17  7]
[50 13 11 99 21 23 33 22 12  0 32 98 96 31 97]
[2. 1. 4. 0. 6. 3. 5.]
[64 27 37 43 35 29 38 53 44 21 61 69 32 59 33 52 39 76  0 51 50 46 26 45
 42 20 55 58 60 56 41 36 48 22 18 25 40 34 31 63  3 73 30 80 24 54 65 47
 70 13 23 74 15 72 49 81 57 66 17 67 93  6 71 19 10  2  7 88  4 62 28 85
 82 75  1 89 68 79 78  8 77 92 84 86 83 12 14 91 11  9  5 16 90 87 98 94
 99 96 97 95]
[50 13 11 99 21 23 33 22 12  0 32 98 96 31 97]
['2' '1' 'N' '3' '0']
[ 2 50  1  0 13 12  9 10 11]


In [ ]:
data_clean['Month'] = data_clean['Month'].replace('0',np.nan)
data_clean['Weekday'] = data_clean['Weekday'].replace('0',np.nan)
data_clean['Num_vehicles'] = data_clean['Num_vehicles'].replace('0',np.nan)

In [ ]:
data_clean = data_clean.replace('N', np.nan)
data_clean = data_clean.dropna()

In [ ]:
print(data_clean['Year'].unique())
print(data_clean['Month'].unique())
print(data_clean['Weekday'].unique())
print(data_clean['Hour'].unique())
print(data_clean['Num_vehicles'].unique())
print(data_clean['Weather_condition'].unique())
print(data_clean['Person_injury_severity'].unique())
print(data_clean['Severity'].unique())
print(data_clean['Collision_configuration'].unique())
print(data_clean['Traffic_control'].unique())
print(data_clean['Person_position'].unique())
print(data_clean['Road_alignment'].unique())
print(data_clean['Person_age'].unique())
print(data_clean['Person_position'].unique())
print(data_clean['Person_injury_severity'].unique())
print(data_clean['Safety_device_used'].unique())

[2015 2016 2017 2018]
[ 1  2  3  4  5  6  7  8  9 10 11 12  0]
[1 2 3 4 5 6 7 0]
[16  7 15  9 12 14  6 18  8 17  2 21 22 19  3 10  0 11 13  5 20 23  1  4]
[ 1  2  3  4  5  6 12 19  8 11  7 17 20  9 10 15 31 22 14 13 47 26 21 18
 37  0 16 51 59]
[2. 4. 1. 3. 7. 6. 5. 0.]
['2' '1' '3' '0']
[2 1]
[ 4 31 21 35  2  3 23 24 22  1 33 50 41  5 32 34  6 36  0 25]
[ 0 18  1 12  6  3 50  2  4  8 15  9  5 16 10 11 13 17  7]
[50 13 11 99 21 23 33 22 12  0 32 98 96 31 97]
[2. 1. 4. 0. 6. 3. 5.]
[64 27 37 43 35 29 38 53 44 21 69 32 59 33 52 39 76  0 51 50 46 26 45 42
 20 55 58 60 56 41 36 48 22 18 61 25 40 34 63  3 73 30 80 24 65 47 31 70
 13 23 54 74 15 72 81 57 17 93  6 66 71 49 19 10  2  7 88  4 62 28 85 82
 75  1 89 67 68 79 78  8 77 92 84 86 83 12 14 91 11  9  5 16 90 87 98 94
 99 96 97 95]
[50 13 11 99 21 23 33 22 12  0 32 98 96 31 97]
['2' '1' '3' '0']
[ 2 50  1  0 13 12  9 10 11]


In [ ]:
X = data_clean.drop('Severity', axis=1)
y = data_clean['Severity']

In [ ]:
from sklearn.feature_selection import SelectKBest, chi2
k = 15
selector = SelectKBest(chi2, k=k)
X_new = selector.fit_transform(X, y)
mask = selector.get_support()
selected_features = X.columns[mask]
selected_features

Index(['Month', 'Weekday', 'Hour', 'Num_vehicles', 'Collision_configuration',
       'Road_configuration', 'Road_surface', 'Road_alignment',
       'Traffic_control', 'Vehicle_type', 'Person_sex', 'Person_age',
       'Person_position', 'Person_injury_severity', 'Safety_device_used'],
      dtype='object')

In [ ]:
data_sel = data_clean[['Num_vehicles', 'Collision_configuration', 'Road_configuration',
       'Road_alignment', 'Traffic_control', 'Vehicle_type', 'Person_age',
       'Person_position', 'Safety_device_used','Severity']]
data_sel

Num_vehicles  Collision_configuration  Road_configuration  \
0                   1                        4                   1   
2                   2                       31                   2   
3                   2                       31                   2   
5                   2                       31                   2   
7                   2                        4                   1   
...               ...                      ...                 ...   
1048569             2                       41                   1   
1048571             1                       50                   1   
1048572             2                       21                   1   
1048573             2                       21                   1   
1048574             2                       21                   1   

         Road_alignment  Traffic_control  Vehicle_type  Person_age  \
0                   2.0                0             1          64   
2                   1.0               18             1          27   
3                   1.0               18             1          37   
5                   1.0               18             1          43   
7                   4.0               18             1          35   
...                 ...              ...           ...         ...   
1048569             1.0               18             1          50   
1048571             1.0               18             1          57   
1048572             1.0               18             1          67   
1048573             1.0               18             1          74   
1048574             1.0               18             1          29   

         Person_position  Safety_device_used  Severity  
0                     50                   2         2  
2                     50                   2         2  
3                     13                   2         2  
5                     50                   2         2  
7                     11                   2         2  
...                  ...                 ...       ...  
1048569               11                   2         2  
1048571               11                   2         2  
1048572               11                   2         2  
1048573               13                   2         2  
1048574               11                   2         2  

[963026 rows x 10 columns]

In [ ]:
X = data_sel.drop('Severity', axis=1)
y = data_sel['Severity']

In [ ]:
data_sel['Severity'].unique()

array([2, 1])

In [ ]:
class_count_1, class_count_2 = data_sel['Severity'].value_counts()
class_1 = data_sel[data_sel['Severity'] == 1]
class_2 = data_sel[data_sel['Severity'] == 2]
print(class_count_1,class_count_2)

947962 15064


In [ ]:
from imblearn.under_sampling import NearMiss
nm = NearMiss()
X_res, y_res = nm.fit_resample(X, y)
X_res.shape, y_res.shape

((30128, 9), (30128,))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score,recall_score,accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.3, random_state=10)

In [ ]:
X_train

Num_vehicles  Collision_configuration  Road_configuration  \
26286             2                       35                   2   
14628             3                       36                   2   
5247              2                       35                   2   
12542             3                       22                   1   
15064             2                       21                   1   
...             ...                      ...                 ...   
28017             1                        6                   1   
17728             2                       21                   1   
29199             2                       36                   2   
7293              2                       35                   2   
17673             2                       35                   2   

       Road_alignment  Traffic_control  Vehicle_type  Person_age  \
26286             1.0                3             1          30   
14628             1.0                1             1          41   
5247              1.0                3             1          20   
12542             2.0               18             1          87   
15064             1.0               18             1          30   
...               ...              ...           ...         ...   
28017             1.0               18             1          29   
17728             1.0               18             1          42   
29199             1.0                1             1          47   
7293              1.0                1             1          21   
17673             1.0                3             1          18   

       Person_position  Safety_device_used  
26286               11                   2  
14628               23                   2  
5247                11                   2  
12542               11                   2  
15064               11                   2  
...                ...                 ...  
28017               11                   2  
17728               11                   2  
29199               11                   2  
7293                11                   2  
17673               13                   2  

[21089 rows x 9 columns]

In [ ]:
y_train

26286    2
14628    1
5247     1
12542    1
15064    2
        ..
28017    2
17728    2
29199    2
7293     1
17673    2
Name: Severity, Length: 21089, dtype: int64

In [ ]:
performance_metrics = pd.DataFrame(columns=['Model', 'Accuracy_Training_Set', 'Accuracy_Test_Set', 'Precision', 'Recall', 'f1_score'])

In [ ]:
ml_models = [LogisticRegression(max_iter=1000),  DecisionTreeClassifier(), RandomForestClassifier()]

In [ ]:
models_list = [LogisticRegression(),
               DecisionTreeClassifier(),
               RandomForestClassifier(),
               ]

In [ ]:
def get_perf_metrics(model, i):
    model_name = type(model).__name__
    print("Training {} model...".format(model_name))
    model.fit(X_train, y_train)
    print("Completed {} model training.".format(model_name))
    y_pred = model.predict(X_test)

    performance_metrics.loc[i] = [
        model_name,
        model.score(X_train, y_train),
        model.score(X_test, y_test),
        precision_score(y_test, y_pred),
        recall_score(y_test, y_pred),
        f1_score(y_test, y_pred),
    ]

    print("Completed {} model's performance assessment.".format(model_name))

In [ ]:
from sklearn.metrics import r2_score,f1_score
for n, model in enumerate(models_list):
    get_perf_metrics(model, n)

Training LogisticRegression model...


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Completed LogisticRegression model training.
Completed LogisticRegression model's performance assessment.
Training DecisionTreeClassifier model...
Completed DecisionTreeClassifier model training.
Completed DecisionTreeClassifier model's performance assessment.
Training RandomForestClassifier model...
Completed RandomForestClassifier model training.
Completed RandomForestClassifier model's performance assessment.


In [ ]:
performance_metrics

Model  Accuracy_Training_Set  Accuracy_Test_Set  \
0      LogisticRegression               0.744701           0.742228   
1  DecisionTreeClassifier               0.948978           0.934617   
2  RandomForestClassifier               0.948978           0.937825   

   Precision    Recall  f1_score  
0   0.838720  0.601412  0.700514  
1   0.977229  0.890311  0.931747  
2   0.980625  0.893622  0.935104

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 42)
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [ ]:
rf = RandomForestClassifier()
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)

In [ ]:
rf_random.best_params_

{'n_estimators': 400,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 100,
 'bootstrap': True}

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

def evaluate(model, X_test, y_test):
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1score = f1_score(y_test, predictions)
    print(f"Model Performance")
    print(f"Accuracy = {accuracy:.2f}")
    print(f"Precision = {precision:.2f}")
    print(f"Recall = {recall:.2f}")
    print(f"F1_Score = {f1score:.2f}")

#Assuming rf_random.best_estimator_ is your trained model:
best_random = rf_random.best_estimator_
evaluate(best_random, X_test, y_test)

Model Performance
Accuracy = 0.94
Precision = 0.98
Recall = 0.89
F1_Score = 0.94
